### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-www#15]
We're missing a favicon to show in the browser's tab

**Comment by darach** [comment]
Done https://www.tremor.rs/favicon.ico

**Comment by Licenser** [comment]
The file is there but it's not showing when visiting the page, so something ti still wrong

**Comment by Licenser** [comment]
for example:
![image](https://user-images.githubusercontent.com/119093/135107861-b9620bec-bed0-490c-8b91-e372b2a39c54.png)

**Comment by Licenser** [comment]
with #89 it's really fixed :D huzza!
